services:
  postgres:
    image: postgres:16
    container_name: fuchibolguessr-postgres
    environment:
      POSTGRES_USER: fuchibol
      POSTGRES_PASSWORD: fuchibol
      POSTGRES_DB: fuchibolguessr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: